preserve_hierarchy: true
commit_message: "[crowdin cron]"
files:
  # documentation
  - source: /website/docs/develop/**/*.md
    translation: /website/%locale%/docs/develop/**/%original_file_name%
    languages_mapping:
      locale:
        zh-CN: zh
  # community pages
  - source: /website/community/**/*.md
    translation: /website/%locale%/community/**/%original_file_name%
    # ignore members since we redirect all locales to EN page for convenience
    ignore:
      - /website/community/members.md
      - /website/zh/community/README.md
    languages_mapping:
      locale:
        zh-CN: zh
  # contribution pages
  - source: /website/contribution/**/*.md
    translation: /website/%locale%/contribution/**/%original_file_name%
    languages_mapping:
      locale:
        zh-CN: zh
  # events pages
  - source: /website/events/**/*.md
    translation: /website/%locale%/events/**/%original_file_name%
    languages_mapping:
      locale:
        zh-CN: zh
  # faq pages
  - source: /website/faq/**/*.md
    translation: /website/%locale%/faq/**/%original_file_name%
    languages_mapping:
      locale:
        zh-CN: zh
  # gallery pages
  - source: /website/gallery/**/*.md
    translation: /website/%locale%/gallery/**/%original_file_name%
    languages_mapping:
      locale:
        zh-CN: zh
  # research pages
  - source: /website/research/**/*.md
    translation: /website/%locale%/research/**/%original_file_name%
    languages_mapping:
      locale:
        zh-CN: zh
  # tutorials pages
  - source: /website/tutorials/**/*.md
    translation: /website/%locale%/tutorials/**/%original_file_name%
    languages_mapping:
      locale:
        zh-CN: zh
  # the index page
  - source: /website/index.md
    translation: /website/%locale%/index.md
    languages_mapping:
      locale:
        zh-CN: zh
