module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  langSidebar: [{type: 'autogenerated', dirName: 'lang'}],
  langapiSidebar: [{type: 'autogenerated', dirName: 'lang-api'}],

  // But you can create a sidebar manually
  /*
  docsSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
