name: PR Build Test

on:
  pull_request:
    branches:
      - master

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Checkout Taichi main repo
        uses: actions/checkout@v2
        with:
          repository: taichi-dev/taichi
          path: source

      - name: Checkout Taichi Autoapi Gen
        uses: actions/checkout@v2
        with:
          repository: taichi-dev/docstring-gen
          path: docsgen

      - name: Set API Gen Env
        run: |
          echo "DOCSTRING_GEN_PATH=${GITHUB_WORKSPACE}/docstring-gen" >> $GITHUB_ENV
          echo "TAICHI_PATH=${GITHUB_WORKSPACE}/taichi/python/taichi" >> $GITHUB_ENV
          echo "TAICHI_WEBSITE=${GITHUB_WORKSPACE}/docs.taichi.graphics" >> $GITHUB_ENV

      - name: Generate New API Docs AND Sync To Docs Website
        run: |
          export DOCSTRING_GEN_PATH=${{ env.DOCSTRING_GEN_PATH }}
          export TAICHI_PATH=${{ env.TAICHI_PATH }}
          export TAICHI_WEBSITE=${{ env.TAICHI_WEBSITE }}
          git fetch origin pull/8/head:MASTER
          $DOCSTRING_GEN_PATH/multi_version_build.sh

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install and Build
        run: yarn --cwd=website install && yarn --cwd=website build
